Docker containers are expected to be short lived.
Once containers serve there purpose they should be disposed off.
Now, if that's the case. We have to have a blue print of some kind to create these containers as and when required.

The blueprint we are talking here is called as images. 
Dockerfile is the declarative way of defining an image. 